### ISSUE TITLE
The second file needed in preprocessing seems invalid anymore

### ISSUE THREAD

**Issue by oatmeal3000** [microsoft/KEAR#11]
https://kaikki.org/dictionary/English/nonsenses.html
The page has been updated and the new file link should be https://kaikki.org/dictionary/English/all-non-inflected-senses/kaikki.org-dictionary-English-all-n-laGJUY  
am I right ?

**Comment by xycforgithub** [comment]
Yes that appears to be the latest version. We used the old version in our experiment - the difference should be minor.

**Comment by sohrab-crowdian** [comment]
Please confirm: the latest url is https://kaikki.org/dictionary/English/all-non-inflected-senses/kaikki_dot_org-dictionary-English-all-non-infl-PIoLCx8T.json   ...?

Have they implemented some randomization in the file name?

**Comment by xycforgithub** [comment]
Yes that file should work. The file names change from time to time but the difference should be minor.
