### ISSUE TITLE
add_knowledge.py refers to incorrect path

### ISSUE THREAD

**Issue by rahmansunny071** [microsoft/KEAR#14]
`python add_knowledge.py` in `/prepocess` refers to the following path `../data/yicxu/wiktionary_new/wik_dict.json` which does not exist in the docker container.

**Comment by xycforgithub** [comment]
Hi @rahmansunny071,
You can use this link for the parsed dictionary:
https://kaikki.org/dictionary/English/all-non-inflected-senses/kaikki_dot_org-dictionary-English-all-non-infl-PIoLCx8T.json

The paths in the codes are only examples.
