### ISSUE TITLE
Retrieval field in the dataset

### ISSUE THREAD

**Issue by chaizmp** [microsoft/KEAR#17]
Hello! Thank you for sharing this amazing work!

I wonder if we can also get the "retrieval" field in the csqa ret dataset (I want to make my own preprocessed dataset.) Do you have any code for retrieving that? Is it about retrieving relevant training examples (q/a pairs) from the question and choice? I tried looking into the code but could not find it.

**Comment by xycforgithub** [comment]
Hi chaizmp,
Thank you for your interest. Please use REINA for the retrieval part of the knowledge:
https://github.com/microsoft/REINA

**Comment by chaizmp** [comment]
I see. Thank you for the fast response!
