### ISSUE TITLE
Missing preprocessing script?

### ISSUE THREAD

**Issue by zixinzeng-jennifer** [microsoft/KEAR#9]
Hi, I'm trying to run your model on a similar QA dataset, but I am wondering which script you used for generating the concepts in question & choices.

**Comment by xycforgithub** [comment]
Hi @zixinzeng-jennifer, The concepts in CommonsenseQA are provided as a part of the dataset, so we do not generate the concepts for question or choices.

**Comment by zixinzeng-jennifer** [comment]
I see, thanks for the reply!
The Entity Linker in spacy can be used for preprocessing.
